@startuml

skinparam sequenceMessageAlign center
hide footbox
'생명선 자동 생성
autoactivate on 

actor "user" as user
participant "식물 사진 관리" as pi
database "식물 사진 DB" as pdb

user -> pi : 식물 사진 삭제 요청(num)

pi -> pdb : 사진 삭제(num)
pdb --> pi : ok
pi --> user : ok 


@enduml